// Tapiracuai Categories - rubros comerciales agrupados por sector
(function(){
  var sectors=[
    {sector:'Alimentos y bebidas',items:['Despensa','Supermercado','Carnicería','Verdulería','Panadería','Confitería','Comida rápida','Restaurante','Heladería','Bodega','Pollería','Rotisería']},
    {sector:'Salud y bienestar',items:['Farmacia','Óptica','Laboratorio','Clínica','Consultorio médico','Odontología','Veterinaria','Gimnasio','Nutrición','Belleza y estética','Peluquería','Barbería']},
    {sector:'Hogar y construcción',items:['Ferretería','Materiales de construcción','Pinturería','Electricidad','Plomería','Carpintería','Mueblería','Vidriería','Decoración','Jardinería','Climatización']},
    {sector:'Moda y personales',items:['Ropa','Calzados','Accesorios','Perfumería','Cosméticos','Joyería','Relojería','Uniformes','Tienda de regalos','Personalizados']},
    {sector:'Tecnología y servicios',items:['Tecnología','Celulares','Informática','Electrónica','Reparación técnica','Imprenta','Fotografía','Diseño gráfico','Internet','Servicios profesionales','Contabilidad','Gestoría']},
    {sector:'Vehículos y repuestos',items:['Repuestos','Taller mecánico','Gomería','Lubricantes','Lavadero','Motos','Autopartes','Chapería y pintura','Auxilio mecánico']},
    {sector:'Servicios locales',items:['Delivery','Transporte','Hospedaje','Hotel','Alquileres','Eventos','Sonido e iluminación','Lavandería','Limpieza','Seguridad','Educación','Academia']},
    {sector:'Campo y producción',items:['Agroveterinaria','Insumos agrícolas','Forrajería','Maquinarias','Semillas','Balanceados','Ganadería','Productos rurales']}
  ];
  function clean(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
  function normalizeName(value){var name=String(value||'').trim();var key=clean(name);var food=['comida rapida','comidas rapidas','fast food','hamburguesa','hamburguesas','pizza','pizzas','pizzeria','pizzerias','empanada','empanadas','lomito','lomitos','pancho','panchos'];if(food.indexOf(key)>-1)return 'Comida rápida';return name}
  function unique(list){var seen=[];return (list||[]).map(normalizeName).filter(function(name){var key=clean(name);if(!name||seen.indexOf(key)>-1)return false;seen.push(key);return true})}
  function all(){return sectors.reduce(function(acc,s){return acc.concat(s.items.map(function(name){return {name:name,sector:s.sector,status:'aprobada',source:'system'}}))},[])}
  function slug(value){return String(value||'categoria').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)}
  function pending(){try{return JSON.parse(localStorage.getItem('tapiracuai_pending_categories')||'[]')}catch(e){return []}}
  function savePending(name,meta){name=normalizeName(name);if(!name)return null;var exists=all().some(function(c){return clean(c.name)===clean(name)});var list=pending();var found=list.find(function(c){return clean(c.name)===clean(name)});if(found)return found;var item={id:'cat_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),name:name,sector:'Otra categoría',status:exists?'aprobada':'pendiente_aprobacion',label:exists?'Aprobada':'Pendiente de aprobación',source:exists?'system':'user',createdAt:new Date().toISOString(),supabaseReady:true,meta:meta||{}};if(!exists){list.push(item);localStorage.setItem('tapiracuai_pending_categories',JSON.stringify(list));if(window.TapiracuaiSupabase&&TapiracuaiSupabase.available&&TapiracuaiSupabase.client){TapiracuaiSupabase.client.from('categorias').insert({nombre:name,slug:slug(name),sector:'Otra categoría',activa:false,pendiente_aprobacion:true}).then(function(res){if(res.error)console.warn('Tapiracuai Supabase categoria:',res.error.message)})}}return item}
  function fillSelect(select,value){if(!select)return;var current=normalizeName(value||select.value||'');select.innerHTML='<option value="">Elegir categoría</option>'+sectors.map(function(s){return '<optgroup label="'+s.sector+'">'+s.items.map(function(i){return '<option value="'+i+'">'+i+'</option>'}).join('')+'</optgroup>'}).join('')+'<option value="__otra__">➕ Otra categoría</option>';select.value=current&&all().some(function(c){return clean(c.name)===clean(current)})?current:(current?'__otra__':'')}
  function setup(opts){opts=opts||{};var search=document.getElementById(opts.searchId);var select=document.getElementById(opts.selectId);var other=document.getElementById(opts.otherId);var status=document.getElementById(opts.statusId);if(!select)return;fillSelect(select,opts.value);function filter(){var q=String(search&&search.value||'').toLowerCase().trim();[].slice.call(select.options).forEach(function(o){if(!o.value||o.value==='__otra__'){o.hidden=false;return}o.hidden=q&&o.text.toLowerCase().indexOf(q)===-1})}function update(){var custom=select.value==='__otra__';if(other)other.closest('.field, label, div').classList.toggle('hidden',!custom);if(status){var customName=custom&&other?other.value.trim():'';status.textContent=custom&&customName?'Pendiente de aprobación para administrador':' ';status.classList.toggle('hidden',!(custom&&customName))}}if(search)search.oninput=filter;select.onchange=update;if(other)other.oninput=update;update()}
  function value(selectId,otherId,meta){var select=document.getElementById(selectId);var other=document.getElementById(otherId);if(!select)return {name:'',status:''};if(select.value==='__otra__'){var item=savePending(other&&other.value,meta);return {name:item?item.name:'',status:item?item.status:'',category:item}}return {name:select.value,status:'aprobada',category:{name:select.value,status:'aprobada',source:'system'}}}
  window.TapiracuaiCategories={sectors:sectors,all:all,pending:pending,savePending:savePending,fillSelect:fillSelect,setup:setup,value:value,normalizeName:normalizeName,unique:unique};
})();
